[build]
  functions = "netlify/functions"
  publish = "public"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[plugins]]
package = "@netlify/plugin-functions-install-core"

[[plugins]]
package = "netlify-plugin-inline-env"
  [plugins.inputs]
  include_files = [
    "public/login/js/env.js"
  ]

