[build]
  command = "node build-script.js"
  functions = "netlify/functions"
  publish = "public"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[plugins]]
package = "@netlify/plugin-functions-install-core"

[[redirects]]
  from = "/dashboard.html"
  to = "/login.html"
  status = 302
  force = true
  conditions = {Role = ["guest"]}



