[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "public"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[context.production.environment]
  FIREBASE_API_KEY = "FIREBASE_API_KEY"
  FIREBASE_AUTH_DOMAIN = "FIREBASE_AUTH_DOMAIN"
  FIREBASE_PROJECT_ID = "FIREBASE_PROJECT_ID"
  FIREBASE_STORAGE_BUCKET = "FIREBASE_STORAGE_BUCKET"
  FIREBASE_MESSAGING_SENDER_ID = "FIREBASE_MESSAGING_SENDER_ID"
  FIREBASE_APP_ID = "FIREBASE_APP_ID"
  FIREBASE_MEASUREMENT_ID = "FIREBASE_MEASUREMENT_ID"

[[plugins]]
package = "@netlify/plugin-functions-install-core"

[build.environment]
  NODE_VERSION = "18"  
