[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "public"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[plugins]]
package = "@netlify/plugin-functions-install-core"




